PEEWEE_CONNECTION = "aiosqlite:///:memory:"

TELEGRAM_API_ID = 10000000
TELEGRAM_API_HASH = "TEST_API_HASH"

TELEGRAM_BOT_NAME = "TestBot"

PYROGRAM_BOT_TOKEN = "1234567890:AaBbCcDdEeFfGgHhIiJjLlMmNn-o_pQqRrS"
